# Generated by Django 5.2.6 on 2025-09-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_group',
            field=models.PositiveIntegerField(choices=[(10, 'große Gruppe'), (2, 'kleine Gruppe'), (0, 'unbegrenzt')], default=0),
        ),
    ]
