# Generated by Django 5.2.6 on 2025-09-24 12:23

import django.core.validators
import events.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_min_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[events.validators.datetime_in_future]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Muss min. 3 Zeichen sein.')]),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('min_group__lte', 10)), name='min_group_less_10'),
        ),
    ]
