# Generated by Django 5.2.6 on 2025-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_date_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='min_group',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'große Gruppe'), (2, 'kleine Gruppe'), (0, 'unbegrenzt')], default=0),
        ),
    ]
